"use client"

import { Card } from "@/components/ui/Card"

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#0A0A0A] pt-32 pb-24 px-6">
      <div className="max-w-4xl mx-auto space-y-12">
        <div className="text-center space-y-4 mb-20">
           <span className="text-[#C5A059] font-bold uppercase tracking-[0.4em] text-[10px] block">InteriorAI Studio</span>
           <h1 className="text-5xl md:text-7xl font-light tracking-tight font-display text-white">Terms & <span className="font-bold">Conditions</span></h1>
           <div className="h-px w-24 bg-[#C5A059] mx-auto mt-8" />
        </div>

        <Card className="p-12 bg-[#0F0F0F] border-white/10 text-slate-400 space-y-8 font-light leading-relaxed">
           <section className="space-y-4">
              <h2 className="text-xl text-white font-bold">1. Introduction</h2>
              <p>Welcome to InteriorAI Studio. By accessing or using our website and services, you agree to be bound by these Terms and Conditions. Please read them carefully.</p>
           </section>

           <section className="space-y-4">
              <h2 className="text-xl text-white font-bold">2. Use of AI Services</h2>
              <p>Our platform provides AI-generated architectural and interior design concepts. These visualizations are for conceptual and inspirational purposes. They do not replace professional architectural plans or structural engineering assessments.</p>
           </section>

           <section className="space-y-4">
              <h2 className="text-xl text-white font-bold">3. Intellectual Property</h2>
              <p>All content generated by InteriorAI remains the intellectual property of the respective users, granting us a non-exclusive license to use the generated content for platform improvement and marketing, unless explicitly stated otherwise in a commercial agreement.</p>
           </section>
        </Card>
      </div>
    </div>
  )
}
