"use client"

import { Card } from "@/components/ui/Card"

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen bg-[#0A0A0A] pt-32 pb-24 px-6">
      <div className="max-w-4xl mx-auto space-y-12">
        <div className="text-center space-y-4 mb-20">
           <span className="text-[#C5A059] font-bold uppercase tracking-[0.4em] text-[10px] block">InteriorAI Studio</span>
           <h1 className="text-5xl md:text-7xl font-light tracking-tight font-display text-white">Legal <span className="font-bold">Disclaimer</span></h1>
           <div className="h-px w-24 bg-[#C5A059] mx-auto mt-8" />
        </div>

        <Card className="p-12 bg-[#0F0F0F] border-white/10 text-slate-400 space-y-8 font-light leading-relaxed">
           <section className="space-y-4">
              <p className="text-lg text-white">
                 The designs, visualizations, and concepts generated by InteriorAI are for illustrative and inspirational purposes only.
              </p>
           </section>

           <section className="space-y-4">
              <h2 className="text-xl text-white font-bold">Not Professional Advice</h2>
              <p>The output generated by our AI does not constitute professional architectural, engineering, or interior design advice. You should always consult with certified professionals before making any structural changes, purchasing furniture based on specific dimensions, or undertaking construction projects.</p>
           </section>

           <section className="space-y-4">
              <h2 className="text-xl text-white font-bold">Accuracy Limitations</h2>
              <p>While our AI strives for realism, dimensions, lighting, and material representations may not be completely accurate or feasible in the real world. InteriorAI accepts no liability for any actions taken based on the visualizations provided.</p>
           </section>
        </Card>
      </div>
    </div>
  )
}
